### PR TITLE
running prepare-dashboard.sh on main without other edits.

### PR DESCRIPTION
**Pull request by simonleandergrimm**
@jeffkaufman I ran prepare-dashboard.sh on a branch that mirrors up-to-date version of main. I am still not sure where the differences originate from.

### CODE REVIEW

**Comment by jeffkaufman** [comment]
This is quite strange: I don't know why there are so many additions across bioprojects.

I can look at this when I get back (Weds) or you and others working this week can look into why it's happening.

**Comment by simonleandergrimm** [comment]
It’s not super urgent. I can take another look and if I don’t resolve it we
can look into it together on Weds.

**Comment by simonleandergrimm** [comment]
> This is quite strange: I don't know why there are so many additions across bioprojects.
> 
> I can look at this when I get back (Weds) or you and others working this week can look into why it's happening.

FYI, I created a new directory with a clean version of mgs-pipeline. Upon running `prepare-dashboard.sh` I still get the following when running git status:

```
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   dashboard/comparison_sample_counts.PRJEB12466.json
	modified:   dashboard/comparison_sample_counts.PRJEB13831.json
	modified:   dashboard/comparison_sample_counts.PRJEB13832.json
	modified:   dashboard/comparison_sample_counts.PRJEB13833.json
	modified:   dashboard/comparison_sample_counts.PRJEB14051.json
	modified:   dashboard/comparison_sample_counts.PRJEB27054.json
	modified:   dashboard/comparison_sample_counts.PRJEB27621.json
	modified:   dashboard/comparison_sample_counts.PRJEB28033.json
	modified:   dashboard/comparison_sample_counts.PRJEB34633.json
	modified:   dashboard/comparison_sample_counts.PRJEB40798.json
	modified:   dashboard/comparison_sample_counts.PRJEB40815.json
	modified:   dashboard/comparison_sample_counts.PRJEB40816.json
	modified:   dashboard/comparison_sample_counts.PRJEB49260.json
	modified:   dashboard/comparison_sample_counts.PRJEB51229.json
	modified:   dashboard/comparison_sample_counts.PRJNA438174.json
	modified:   dashboard/comparison_sample_counts.PRJNA527877.json
	modified:   dashboard/comparison_sample_counts.PRJNA603194.json
	modified:   dashboard/comparison_sample_counts.PRJNA645711.json
	modified:   dashboard/comparison_sample_counts.PRJNA661613.json
	modified:   dashboard/comparison_sample_counts.PRJNA681566.json
	modified:   dashboard/comparison_sample_counts.PRJNA729801.json
	modified:   dashboard/comparison_sample_counts.PRJNA774620.json
	modified:   dashboard/comparison_sample_counts.PRJNA812772.json
	modified:   dashboard/comparison_sample_counts.PRJNA853368.json
	modified:   dashboard/comparison_sample_counts.PRJNA875025.json
	modified:   dashboard/comparison_sample_counts.PRJNA924011.json
	modified:   dashboard/comparison_sample_counts.PRJNA943189.json
	modified:   dashboard/comparison_sample_counts.PRJNA966185.json
	modified:   dashboard/comparison_taxid_classifications.json
	modified:   dashboard/comparison_taxids.txt
	modified:   dashboard/taxonomic_names.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	bioprojects/PRJNA853368/metadata/head.n_reads
	bioprojects/PRJNA853368/metadata/tail.n_reads
	bioprojects/PRJNA853368/metadata/test.n_reads

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by jeffkaufman** [comment]
After 2e34c20, when I run it on main with no edits it gives me no changes; is that also what you see now?

**Comment by simonleandergrimm** [comment]
> After [2e34c20](https://github.com/naobservatory/mgs-pipeline/commit/2e34c208c524890fc995232b8e067a5a620e09dc), when I run it on main with no edits it gives me no changes; is that also what you see now?

Yep this is also what I see!

**Comment by simonleandergrimm** [comment]
Closing this PR given that Jeff's fix resolved this issue.

**Pull request closed without merging**
